[package]
name = "gogo"
version = "0.1.0"
authors = ["Rahul Garg <rg@vihu.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
dotenv = "0.15.0"
rocksdb = "0.15.0"
url = "2.2.0"
