[package]
name = "gogo"
version = "0.4.0"
authors = ["Rahul Garg <rg@vihu.dev>"]
edition = "2018"
description = "A mnemonic terminal url opener"
homepage = "https://github.com/vihu/gogo"
repository = "https://github.com/vihu/gogo"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rocksdb = "0.15.0"
url = "2.2.0"
colored = "2.0.0"
prettytable-rs = "^0.8"
